### ISSUE TITLE
impossibilité de changé la langue

### ISSUE THREAD

**Issue by leaderfox09** [skarab42/marv-site#1]
Hello,

Lorsque je souhaite changé de langue du programme (de FR à EN par exemple), il redémarre mais garde toujours le FR.
Il reste sur la langue de base du système.

OS: Windows 10
Langue système: FR
Version Marv: v1.1.0

**Comment by skarab42** [comment]
Ha tu l'a posté ici, je la trouvais pas^^ Les issue pour Marv c'est ici https://github.com/skarab42/marv/issues. 
Et c'est corrigé si jamais :) Merci pour le repport !

**Comment by skarab42** [comment]
F.I : https://github.com/skarab42/marv/issues/73
